# Site settings
title: "mos_"
main:
  title: "mos_ | where I develop my ideas and notes about development"
header-img: img/home-bg2.jpg
email: pan.g@krutt.org
description: "notes and ideas about my life as a lazy developer written probably with an IDE in dark mode"
baseurl: ""
url: "https://kmos.github.io/jekyll_blog/"
twitter_username: nmosf
github_username:  kmos
linkedin_username: giovannipanice
email_username:  pan.g@krutt.org
author: nmosf
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
comments: true
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

defaults:
  - scope:
      path: "img"
    values:
      image: true

plugins:
  - jekyll-analytics
  - jekyll-seo-tag

jekyll_analytics:
  GoogleAnalytics:              # Add, if you want to track with Google Analytics
    id: UA-168994403-1         # Required - replace with your tracking id
    anonymizeIp: false        # Optional - Default: false - set to true for anonymized tracking

twitter:
  username: nmosf
  card: summary

social:
  name: Giovanni Panice
  links:
    - https://twitter.com/nmosf
    - https://www.linkedin.com/in/giovannipanice/
    - https://github.com/kmos